name: deepngs_pub
channels:
  - pyg
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10.*
  - pytorch=2.1.2
  - numpy<2
  - pandas
  - scipy
  - matplotlib
  - scikit-learn
  - openssl
  - pip
  - pip:
    - s3fs
    - boto3==1.34.34
    - botocore==1.34.34
    - fonttools==4.48.1
    - huggingface-hub==0.20.3
    - ipython==8.21.0
    - ipywidgets==8.1.2
    - jedi==0.19.1
    - jupyterlab-widgets==3.0.10
    - lit==17.0.6
    - pytorch-lightning
    - logomaker==0.8
    - matplotlib-inline==0.1.6
    - pillow==10.2.0
    - regex==2023.12.25
    - s3transfer==0.10.0
    - safetensors==0.4.2
    - seaborn==0.13.2
    - transformers==4.37.2
    - umap-learn==0.5.5
    - universal-pathlib==0.1.4
    - wandb==0.16.3
    - wcwidth==0.2.13
    - pre-commit
    - psutil
    - appdirs
    - requests
    - ablang
    - sequmap
    - hdbscan
    - biopython
    - python-igraph
    - leidenalg
